### ISSUE TITLE
TouchEvent is not defined

### ISSUE THREAD

**Issue by sonyan** [bokuweb/react-rnd#171]
Just upgraded to 6.0.0 and got the following compile error:
/Users/sonyan/Projects/zen/node_modules/react-rnd/src/index.js:11
export class TouchEvent2 extends TouchEvent {
                                 ^
ReferenceError: TouchEvent is not defined
    at Object.<anonymous> (/Users/sonyan/Projects/zen/node_modules/react-rnd/src/index.js:11:34)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sonyan/Projects/zen/build/webpack:/external "react-rnd":1:1)
    at __webpack_require__ (/Users/sonyan/Projects/zen/build/webpack:/webpack/bootstrap d404054d4d1b00ce092e:19:1)
    at Object.<anonymous> (/Users/sonyan/Projects/zen/build/webpack:/components/Graph/components/Object/ImageNode.js:3:1)
    at __webpack_require__ (/Users/sonyan/Projects/zen/build/webpack:/webpack/bootstrap d404054d4d1b00ce092e:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/sonyan/Projects/zen/build/webpack:/components/Graph/components/Object/Node.js:3:1)
    at __webpack_require__ (/Users/sonyan/Projects/zen/build/webpack:/webpack/bootstrap d404054d4d1b00ce092e:19:1)
    at Object.<anonymous> (/Users/sonyan/Projects/zen/build/webpack:/components/Graph/components/Stage/Stage.js:20:1)
    at __webpack_require__ (/Users/sonyan/Projects/zen/build/webpack:/webpack/bootstrap d404054d4d1b00ce092e:19:1)
/Users/sonyan/Projects/zen/tools/runServer.js:80
          throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);

**Comment by bokuweb** [comment]
@sonyan Thanks for your report :) I've published v6.0.1. Could you please try it?

**Comment by sonyan** [comment]
it works

**Comment by bokuweb** [comment]
Sorry, I had already 7.0.0 published
